version: '3'
services:
    
        
    nginx:
        build: 
            context: ./nginx/
            dockerfile: ./Dockerfile
        ports:
            - 8000:8000
            - 8001:8001
            - 8002:8002
        
